name: build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v4
      - name: Install most mimseq deps with conda
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: .github/environment.yml
          cache-environment: false
          cache-downloads: true
          generate-run-shell: true
          create-args: |
            python=${{ matrix.python-version }}
      - name: Install usearch
        run: |
          wget https://drive5.com/downloads/usearch10.0.240_i86linux32.gz
          gunzip usearch10.0.240_i86linux32.gz
          chmod +x usearch10.0.240_i86linux32
          mv usearch10.0.240_i86linux32 /usr/local/bin/usearch
        shell: micromamba-shell {0}
      - name: Install mimseq
        run: |
          python -m pip install --upgrade pip setuptools
          pip install .
        shell: micromamba-shell {0}
      - name: Test
        run: |
          pytest
        shell: micromamba-shell {0}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mimseq-output
          path: "test_*"

  build-status: # for branch protection rule
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - name: Successful build
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing build
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
